#pragma once

#define VIAL_KEYBOARD_UID {0x66, 0x83, 0x14, 0xE8, 0x5D, 0x1E, 0xD0, 0x47}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
#define LAYER_STATE_8BIT
#define NO_MUSIC_MODE
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
